# Generated by Django 5.1.3 on 2025-12-30 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_category_product_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ชื่อบริษัท/ร้านค้า")),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ชื่อผู้ติดต่อ"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="เบอร์โทรศัพท์"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="ที่อยู่"),
                ),
                (
                    "line_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Line ID"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="alert_level",
            field=models.IntegerField(default=5, verbose_name="แจ้งเตือนเมื่อต่ำกว่า"),
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="รหัสบาร์โค้ด",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ราคาทุน"
            ),
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("IN", "🟢 รับเข้า (ซื้อเพิ่ม/รับคืน)"),
                            ("OUT", "🔴 จ่ายออก (ขาย/เบิกใช้)"),
                            ("ADJUST", "🟠 ปรับปรุง (ของหาย/นับสต็อก)"),
                        ],
                        max_length=10,
                        verbose_name="ประเภทรายการ",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="จำนวน")),
                (
                    "price_at_time",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคาต่อหน่วย(ตอนทำรายการ)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ทำรายการ"),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ทำรายการ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.product",
                        verbose_name="สินค้า",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employees.supplier",
                verbose_name="ซัพพลายเออร์",
            ),
        ),
    ]
