# Generated by Django 5.1.3 on 2025-12-30 08:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_supplier_product_alert_level_product_barcode_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("FG", "สินค้าสำเร็จรูป (Finished Good)"),
                    ("RM", "วัตถุดิบ (Raw Material)"),
                ],
                default="FG",
                max_length=2,
                verbose_name="ประเภทสินค้า",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบสั่งซื้อ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่สั่ง"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "📝 รอดำเนินการ (Draft)"),
                            ("ORDERED", "📞 สั่งของแล้ว (Ordered)"),
                            ("RECEIVED", "✅ รับของแล้ว (Received)"),
                            ("CANCELLED", "❌ ยกเลิก (Cancelled)"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ยอดรวม",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้สั่งซื้อ",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.supplier",
                        verbose_name="ซัพพลายเออร์",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="จำนวน")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="ราคาต่อหน่วย (ทุน)"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="ราคารวม",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="employees.purchaseorder",
                    ),
                ),
            ],
        ),
    ]
