# Generated by Django 5.1.3 on 2025-12-31 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_product_product_type_purchaseorder_purchaseorderitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BOMItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(default=1.0, verbose_name="จำนวนที่ใช้ (ต่อ 1 ชิ้น)"),
                ),
                (
                    "finished_good",
                    models.ForeignKey(
                        limit_choices_to={"product_type": "FG"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_items",
                        to="employees.product",
                        verbose_name="สินค้าที่ผลิต (FG)",
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        limit_choices_to={"product_type": "RM"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_bom",
                        to="employees.product",
                        verbose_name="วัตถุดิบที่ใช้ (RM)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="จำนวนที่ผลิต"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "รอผลิต"),
                            ("IN_PROGRESS", "กำลังผลิต"),
                            ("COMPLETED", "ผลิตเสร็จสิ้น (ตัดสต็อก)"),
                            ("CANCELLED", "ยกเลิก"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้สั่งผลิต",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        limit_choices_to={"product_type": "FG"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.product",
                        verbose_name="สินค้าที่จะผลิต",
                    ),
                ),
            ],
        ),
    ]
