# Generated by Django 5.1.3 on 2025-12-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_bomitem_productionorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionorder",
            name="job_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="เลขที่ใบงาน (JOB)",
            ),
        ),
    ]
