# Generated by Django 5.1.3 on 2026-01-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_productionorder_job_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_th",
                    models.CharField(
                        default="บริษัท เจซี จำกัด",
                        max_length=200,
                        verbose_name="ชื่อบริษัท (ไทย)",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ชื่อบริษัท (อังกฤษ)"
                    ),
                ),
                ("address", models.TextField(verbose_name="ที่อยู่บริษัท")),
                (
                    "tax_id",
                    models.CharField(max_length=20, verbose_name="เลขประจำตัวผู้เสียภาษี"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="เบอร์โทรศัพท์"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="อีเมล"),
                ),
                ("website", models.URLField(blank=True, verbose_name="เว็บไซต์")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company_logo/",
                        verbose_name="โลโก้บริษัท",
                    ),
                ),
            ],
            options={
                "verbose_name": "ข้อมูลบริษัท",
                "verbose_name_plural": "ข้อมูลบริษัท (ตั้งค่า)",
            },
        ),
    ]
