# Generated by Django 5.1.3 on 2026-01-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_companyinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="signature",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company_signatures/",
                verbose_name="ลายเซ็น+ตราประทับ",
            ),
        ),
    ]
