# Generated by Django 5.1.3 on 2026-01-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="เช่น CUS-001",
                        max_length=20,
                        unique=True,
                        verbose_name="รหัสลูกค้า",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="ชื่อลูกค้า / บริษัท"),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        default="สำนักงานใหญ่",
                        max_length=100,
                        verbose_name="สาขา",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="เลขผู้เสียภาษี"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ชื่อผู้ติดต่อ"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="เบอร์โทรศัพท์"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="อีเมล"
                    ),
                ),
                (
                    "line_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Line ID"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=255, verbose_name="ที่อยู่ (เลขที่/หมู่บ้าน/ถนน)"
                    ),
                ),
                (
                    "sub_district",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ตำบล/แขวง"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="อำเภอ/เขต"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="จังหวัด"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="รหัสไปรษณีย์"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="วงเงินเครดิต",
                    ),
                ),
                (
                    "credit_term",
                    models.IntegerField(default=0, verbose_name="เครดิต (วัน)"),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="สถานะใช้งาน"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ลูกค้า",
                "verbose_name_plural": "ฐานข้อมูลลูกค้า",
                "ordering": ["code"],
            },
        ),
    ]
