# Generated by Django 5.1.3 on 2026-01-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="location",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="พิกัด GPS / Google Maps Link",
            ),
        ),
    ]
