# Generated by Django 5.1.3 on 2026-01-01 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0006_productionorder_job_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qt_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ QT"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="วันที่"
                    ),
                ),
                ("valid_until", models.DateField(verbose_name="ยืนยันราคาถึง")),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="ชื่อลูกค้า"),
                ),
                (
                    "customer_address",
                    models.TextField(blank=True, null=True, verbose_name="ที่อยู่"),
                ),
                (
                    "customer_tax_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="เลขผู้เสียภาษี"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "ร่างเอกสาร"),
                            ("SENT", "ส่งให้ลูกค้าแล้ว"),
                            ("APPROVED", "อนุมัติ/สั่งซื้อแล้ว"),
                            ("REJECTED", "ปฏิเสธ"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.product",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.quotation",
                    ),
                ),
            ],
        ),
    ]
