# Generated by Django 5.1.3 on 2026-01-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="ชื่อลูกค้า / ชื่อบริษัท"),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True,
                        default="สำนักงานใหญ่",
                        max_length=100,
                        null=True,
                        verbose_name="สาขา",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="เลขผู้เสียภาษี"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="ที่อยู่"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="เบอร์โทรศัพท์"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="อีเมล"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ชื่อผู้ติดต่อ"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ฐานข้อมูลลูกค้า",
                "verbose_name_plural": "ฐานข้อมูลลูกค้า (Customers)",
            },
        ),
    ]
