# Generated by Django 5.1.3 on 2026-01-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="อำเภอ/เขต"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="facebook",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Facebook"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="line_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Line ID"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="note",
            field=models.TextField(
                blank=True, null=True, verbose_name="หมายเหตุ/ความสนใจ"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="รหัสไปรษณีย์"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="province",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="จังหวัด"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="sub_district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ตำบล/แขวง"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ที่อยู่ (เลขที่/หมู่บ้าน/ถนน/ซอย)",
            ),
        ),
    ]
