# Generated by Django 5.1.3 on 2026-01-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_customer_district_customer_facebook_customer_line_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name_th", models.CharField(max_length=150)),
                ("name_en", models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name="quotation",
            name="customer_district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="อำเภอ/เขต"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="customer_phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="เบอร์โทรศัพท์"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="customer_province",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="จังหวัด"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="customer_sub_district",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ตำบล/แขวง"
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="customer_zip",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="รหัสไปรษณีย์"
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="customer_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ที่อยู่ (เลขที่/หมู่บ้าน)"
            ),
        ),
        migrations.CreateModel(
            name="Amphure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name_th", models.CharField(max_length=150)),
                ("name_en", models.CharField(max_length=150)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amphures",
                        to="sales.province",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tambon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_code", models.CharField(max_length=10)),
                ("name_th", models.CharField(max_length=150)),
                ("name_en", models.CharField(max_length=150)),
                (
                    "amphure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tambons",
                        to="sales.amphure",
                    ),
                ),
            ],
        ),
    ]
