# Generated by Django 5.1.3 on 2026-01-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_province_quotation_customer_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="quotation",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
