# Generated by Django 5.1.3 on 2026-01-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_quotation_discount_quotation_shipping_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="ส่วนลด"
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="ค่าขนส่ง"
            ),
        ),
    ]
