# Generated by Django 5.1.3 on 2026-01-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_quotation_discount_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
