# Generated by Django 5.1.3 on 2026-01-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_delete_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="customer_address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ที่อยู่"
            ),
        ),
    ]
